#!/usr/bin/env node
'use strict';

// Minifies the dashboard's own JavaScript and CSS.
//
// The first-party assets shipped exactly as authored: 256 KB of
// guild-settings.js, an 88 KB stylesheet and 32 KB of settings-payload.js, all
// of it comments and indentation and names chosen for a reader. `compression`
// gzips it on the way out, which shrinks the transfer and does nothing about
// the parse — the browser still expands, tokenises and compiles every byte, on
// whatever phone is being used for a quick settings change (#905).
//
// The output goes next to the input as a `.min` twin, which is what asset()
// looks for: `/styles.css` resolves to `/styles.min.css` when one is there and
// to the original when it is not. So this is optional by construction. A
// checkout run straight with `npm start` serves the readable files exactly as
// it did before; the Docker image runs this in a build stage and serves the
// small ones. Nothing in the views changes either way, and the content hash
// asset() already stamps onto the URL does the cache busting.
//
// The twins are generated, not source: .gitignore keeps them out of the repo,
// so there is no committed artifact to fall out of step with the file it was
// built from. What guards the one thing minification could break — this page
// reaches its own top-level functions from inline `onclick` attributes, so a
// renamed top-level binding is a broken button — is
// tests/dashboardMinifiedAssets.test.js, which checks that every top-level name
// survives. esbuild only renames top-level identifiers when bundling, and this
// deliberately does not bundle.
//
//   npm run build:assets                write the .min twins into public/
//   npm run build:assets -- --out DIR   write them somewhere else instead
//
// Requires an installed node_modules (esbuild is a devDependency, and is
// exact-pinned for the same reason chart.js is: it decides the bytes that ship).

const fs = require('fs');
const path = require('path');
const esbuild = require('esbuild');

const PUBLIC = path.join(__dirname, '..', 'src', 'dashboard', 'public');

// Ours, and served on a dashboard page. public/vendor/chart.umd.min.js is
// already minified upstream and is not ours to rebuild; public/fonts/fonts.css
// is generated by scripts/fetch-fonts.sh and is a few hundred bytes of
// @font-face.
const SOURCES = [
    'esc-html.js',
    'settings-payload.js',
    'guild-settings.js',
    'styles.css',
];

/** `guild-settings.js` -> `guild-settings.min.js` */
function minifiedName(file) {
    const ext = path.extname(file);
    return `${file.slice(0, -ext.length)}.min${ext}`;
}

/**
 * Minify one file's contents.
 *
 * Synchronous so that a caller with nowhere to await — tests/helpers boots
 * the page from these to prove the minified files still drive it — can use the
 * same function the build does, rather than a second copy of these options.
 *
 * Deliberately not a bundle. These are classic scripts, not modules: the inline
 * bootstrap block, the EJS `onclick` attributes and the other two files all
 * reach guild-settings.js's top-level functions by name off the global object.
 * Bundling would wrap the file in a scope and rename them, and every inline
 * handler on the page would stop resolving. Without `bundle`, esbuild leaves
 * top-level names alone and renames only what is genuinely local.
 */
function minify(source, file) {
    const { code } = esbuild.transformSync(source, {
        loader: path.extname(file) === '.css' ? 'css' : 'js',
        minify: true,
        // The dashboard's browser support is whatever runs Discord; nothing
        // here needs downlevelling, and a transform that rewrites syntax is a
        // transform that can change behaviour. Minify only.
        target: 'es2020',
        sourcefile: file,
    });
    return code;
}

function main() {
    const outIndex = process.argv.indexOf('--out');
    const outDir = outIndex === -1 ? PUBLIC : path.resolve(process.argv[outIndex + 1]);
    fs.mkdirSync(outDir, { recursive: true });

    let before = 0;
    let after = 0;

    for (const file of SOURCES) {
        const source = fs.readFileSync(path.join(PUBLIC, file), 'utf8');
        const code = minify(source, file);
        fs.writeFileSync(path.join(outDir, minifiedName(file)), code);

        before += Buffer.byteLength(source);
        after += Buffer.byteLength(code);
        console.log(
            `${file.padEnd(22)} ${String(Buffer.byteLength(source)).padStart(7)} -> ` +
            `${String(Buffer.byteLength(code)).padStart(7)} bytes`
        );
    }

    const saved = Math.round((1 - after / before) * 100);
    console.log(`\nWrote ${SOURCES.length} files into ${outDir} (${saved}% smaller).`);
}

if (require.main === module) {
    try {
        main();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
}

module.exports = { PUBLIC, SOURCES, minifiedName, minify };
