#!/usr/bin/env node
'use strict';

// Renders docs/ECONOMY_ITEMS.md — every named thing in the economy, with the id
// the code stores it under.
//
//   npm run docs:items             rewrite docs/ECONOMY_ITEMS.md
//   npm run docs:items -- --check  exit 1 if the file is out of date
//
// `--check` is what tests/itemDocs.test.js runs, so adding a weapon, a fish, an
// ore, a shop item or an event loot table turns `npm test` red until the file
// is regenerated.
//
// ── Why this exists ─────────────────────────────────────────────────────────
//
// Item art is matched to items by id, not by eye: `getItemImageAttachment` in
// src/utils/itemImageHelper.js looks up an `ItemImage` by the same id the
// command asked for, and the upload route in
// src/dashboard/routes/api/itemImages.js rejects any id the game data does not
// name. So anyone drawing icons needs the ids — all of them, spelled exactly —
// and reading them out of eight data modules by hand is how a set of 500 icons
// ends up with a dozen filed under a name nothing ever asks for.
//
// Every row here is read off the data at run time. Nothing is restated, which
// is the only property that keeps a list this long true a month from now.
//
// ── What counts as an item ──────────────────────────────────────────────────
//
// Loosely, on purpose. The gear, consumables, catches, materials and shop
// stock are the inventory proper. Zones, depths, locations, regions and the
// event currencies are not held in an inventory but are drawn beside the items
// in the shop and activity views, and the upload route already accepts the
// first three. The last section — jobs, bosses, weather, heist roles — is
// named content that nothing renders an item image for today; it is listed
// under its own heading so a reader can tell the difference at a glance rather
// than discovering it at upload time.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DOC_PATH = path.join(ROOT, 'docs', 'ECONOMY_ITEMS.md');

const BANNER =
    '<!-- Generated by scripts/docs-items.js — run `npm run docs:items` after changing the economy data. -->';

const hunt = require('../src/data/huntData');
const fish = require('../src/data/fishData');
const mine = require('../src/data/mineData');
const explore = require('../src/data/exploreData');
const cross = require('../src/data/crossSystemData');
const seasonal = require('../src/data/seasonalEvents');
const heist = require('../src/data/heistData');
const jobs = require('../src/data/defaultJobs');
const { DROP_TABLE, RARE_DROP_TABLE } = require('../src/data/dailyDropTable');
const { MATERIAL_RARITY, TIER_LABELS } = require('../src/data/materialRarity');
const { DEFAULT_SHOP_ITEMS } = require('../src/data/defaultShopItems');
const { ACTIVITY_ITEMS, ACTIVITY_ITEM_IDS } = require('../src/data/activityItems');
const { PET_DEFINITIONS } = require('../src/services/petService');

// ── Row builders ────────────────────────────────────────────────────────────
//
// Tiered gear is keyed by `slug` and everything else by `id`, the same split
// activityItems.js honours; the namespace prefix is what the hunt/fish/mine
// views ask an image for, so it is part of the id printed here.

/** One table row: the id the code uses, the label a user sees, its emoji. */
function row(item, { namespace = '', idField = 'id', id = null } = {}) {
    const raw = id ?? item[idField];
    return {
        id: namespace ? `${namespace}:${raw}` : String(raw),
        name: item.name || item.label || String(raw),
        emoji: item.emoji || '',
    };
}

const rowsFrom = (list, opts) => list.map(item => row(item, opts));
const rowsOf = (obj, opts) => rowsFrom(Object.values(obj), opts);

/** Keyed collections whose entries carry no id of their own (traits, bosses). */
const rowsByKey = obj => Object.entries(obj).map(([key, value]) => row(value, { id: key }));

/** A pipe in a name would split the cell it is printed in. */
const escapeCell = text => String(text).replace(/\|/g, '\\|');

function renderTable(rows) {
    const lines = ['| Item ID | Name | Emoji |', '|---|---|---|'];
    for (const r of rows) lines.push(`| \`${r.id}\` | ${escapeCell(r.name)} | ${r.emoji} |`);
    return lines.join('\n');
}

/**
 * A `### heading` with its row count, then the table.
 *
 * Rows are deduplicated by id: a drop table can roll the same item at two
 * different streak milestones, and an item printed twice in a list of names is
 * an item somebody draws twice.
 */
function section(title, rows) {
    if (!rows.length) throw new Error(`docs-items: "${title}" produced no rows`);
    const unique = [...new Map(rows.map(r => [r.id, r])).values()];
    return `### ${title} (${unique.length})\n\n${renderTable(unique)}\n`;
}

// ── The sections ────────────────────────────────────────────────────────────

function huntSections() {
    return [
        section('Weapons', rowsFrom(hunt.WEAPON_TIERS, { namespace: 'hunt', idField: 'slug' })),
        section('Weapon Upgrades', rowsOf(hunt.WEAPON_UPGRADES, { namespace: 'hunt' })),
        section('Ammo Packs', rowsFrom(hunt.AMMO_PACKS, { namespace: 'hunt' })),
        section('Consumables', rowsOf(hunt.CONSUMABLES, { namespace: 'hunt' })),
        section('Zones', rowsFrom(hunt.ZONE_LIST, { namespace: 'hunt' })),
        section('Animals', rowsOf(hunt.ANIMALS, { namespace: 'hunt' })),
        section('Craft Recipes', rowsOf(hunt.CRAFT_RECIPES)),
        section('Field Trophies', rowsByKey(hunt.FIELD_TROPHIES)),
    ].join('\n');
}

function fishSections() {
    return [
        section('Rods', rowsFrom(fish.ROD_TIERS, { namespace: 'fish', idField: 'slug' })),
        section('Rod Upgrades', rowsOf(fish.ROD_UPGRADES, { namespace: 'fish' })),
        section('Bait Packs', rowsFrom(fish.BAIT_PACKS, { namespace: 'fish' })),
        section('Consumables', rowsOf(fish.CONSUMABLES, { namespace: 'fish' })),
        section('Locations', rowsFrom(fish.LOCATION_LIST, { namespace: 'fish' })),
        section('Fish', rowsOf(fish.FISH, { namespace: 'fish' })),
        section('Junk', rowsFrom(fish.JUNK_ITEMS, { namespace: 'fish' })),
        section('Treasure', rowsFrom(fish.TREASURE_ITEMS, { namespace: 'fish' })),
        section('Craft Recipes', rowsOf(fish.FISH_CRAFT_RECIPES)),
    ].join('\n');
}

function mineSections() {
    return [
        section('Pickaxes', rowsFrom(mine.PICKAXE_TIERS, { namespace: 'mine', idField: 'slug' })),
        section('Pickaxe Upgrades', rowsOf(mine.PICKAXE_UPGRADES, { namespace: 'mine' })),
        section('Blast Packs', rowsFrom(mine.BLAST_PACKS, { namespace: 'mine' })),
        section('Consumables', rowsOf(mine.CONSUMABLES, { namespace: 'mine' })),
        section('Depths', rowsFrom(mine.DEPTH_LIST, { namespace: 'mine' })),
        section('Ores', rowsOf(mine.ORES, { namespace: 'mine' })),
        section('Craft Recipes', rowsOf(mine.CRAFT_RECIPES)),
    ].join('\n');
}

// Relics are the one collection whose `itemId` is the display name — the field
// holds "Whisperwood Charm", spaces and all, and that string is what the relic
// case stores and looks up. Printed as-is rather than tidied into snake_case,
// because a tidied id here would not match anything.
function exploreSections() {
    const relics = explore.RELIC_LIST.map(relic => ({
        id: relic.itemId,
        name: relic.itemId,
        emoji: explore.RELIC_EMOJI[relic.rarity] || '',
    }));

    return [
        section('Regions', rowsFrom(explore.REGION_LIST)),
        section('Relics', relics),
    ].join('\n');
}

function materialSections() {
    const bySource = source =>
        Object.entries(MATERIAL_RARITY)
            .filter(([, meta]) => meta.source === source)
            .map(([id, meta]) => ({
                // Materials answer to `material:`, not to the system that drops
                // them: a hunt trophy is an ingredient in a fishing recipe, and
                // the game keys them all in one flat space for exactly that.
                id: `material:${id}`,
                name: `${meta.label} — ${TIER_LABELS[meta.tier] || `Tier ${meta.tier}`}`,
                emoji: meta.emoji || '',
            }));

    return [
        section('Hunt Materials', bySource('hunt')),
        section('Fish Materials', bySource('fish')),
        section('Mine Materials', bySource('mine')),
        section('Explore Materials', bySource('explore')),
    ].join('\n');
}

// Shop items carry no emoji field; theirs is the first character of the
// description, which is where /shop reads it from too.
function shopSections() {
    const CATEGORIES = [
        ['standard', 'Standard'],
        ['prestige', 'Prestige'],
        ['endgame', 'Endgame Cosmetics'],
        ['black_market', 'Black Market — Prestige I+'],
        ['p8_black_market', 'Black Market — Prestige VIII+'],
    ];

    const known = new Set(CATEGORIES.map(([key]) => key));
    const uncategorised = DEFAULT_SHOP_ITEMS
        .map(item => item.category)
        .filter(category => category && !known.has(category));
    if (uncategorised.length) {
        throw new Error(`docs-items: unknown shop categories: ${[...new Set(uncategorised)].join(', ')}`);
    }

    return CATEGORIES.map(([key, title]) =>
        section(
            title,
            DEFAULT_SHOP_ITEMS
                .filter(item => (item.category || 'standard') === key)
                .map(item => ({
                    id: item.itemId,
                    name: item.name,
                    emoji: (item.description.match(/^\S+/) || [''])[0],
                })),
        ),
    ).join('\n');
}

function seasonalSections() {
    return Object.values(seasonal.SEASONAL_EVENTS).map(event => {
        const parts = [`### ${event.emoji} ${event.name} — \`${event.id}\``, ''];

        parts.push(renderTable([
            { id: event.currency.id, name: `${event.currency.name} (event currency)`, emoji: event.currency.emoji },
            { id: event.lootBox.itemId, name: `${event.lootBox.name} (loot box)`, emoji: event.lootBox.emoji },
        ]), '');

        parts.push(`**Loot box contents (${event.lootBox.items.length})**`, '', renderTable(rowsFrom(event.lootBox.items, { idField: 'itemId' })), '');

        if (event.shop?.length) {
            parts.push(`**Event shop (${event.shop.length})**`, '', renderTable(rowsFrom(event.shop, { idField: 'itemId' })), '');
        }
        return parts.join('\n');
    }).join('\n');
}

// Named content the item-image system does not read today. Kept apart from the
// items above so nobody draws forty job icons the bot has nowhere to show.
function flavourSections() {
    const targets = Object.entries(heist.TARGETS).map(([id, target]) => ({
        id, name: target.label, emoji: target.emoji || '',
    }));

    return [
        section('Jobs', jobs.map(job => row(job, { id: job.name.toLowerCase().replace(/\s+/g, '_') }))),
        section('Hunt Apex Bosses', rowsByKey(hunt.APEX_TYPES)),
        section('Fishing Bosses', rowsByKey(fish.BOSS_TYPES)),
        section('Animal Traits', rowsOf(hunt.ANIMAL_TRAITS)),
        section('Fishing Weather', rowsOf(fish.WEATHER_TYPES)),
        section('Cross-System Synergies', rowsOf(cross.SYNERGIES)),
        section('Heist Roles', rowsByKey(heist.ROLES)),
        section('Heist Targets', targets),
    ].join('\n');
}

/** The ids the upload route accepts today, grouped the way the panel shows them. */
function uploadableIndex() {
    const lines = [];
    for (const [namespace, groups] of Object.entries(ACTIVITY_ITEMS)) {
        for (const [group, items] of Object.entries(groups)) {
            lines.push(`# ${namespace} — ${group}`);
            for (const item of items) lines.push(`${item.id}    ${item.label}`);
            lines.push('');
        }
    }
    return lines.join('\n').trimEnd();
}

// ── The document ────────────────────────────────────────────────────────────

function buildDoc() {
    const activityCount = ACTIVITY_ITEM_IDS.size;

    const doc = `${BANNER}

# Economy Item Names

Every named thing in the economy, with the id the code stores it under. The ids
are what item art is matched by — \`getItemImageAttachment\` looks an image up by
the id the command asked for — so an icon filed under anything else is an icon
nothing renders.

**Reading the ids.** A hunt, fish or mine item is prefixed with its activity and
a material with \`material:\` — that prefix is part of the id the image system
stores and looks the item up by. The part after the colon is what the game data
calls the thing, and is what a recipe or an inventory names it by.

**Naming image files.** Use the item id verbatim, replacing the \`:\` with \`_\`
(\`hunt:wooden_rifle\` → \`hunt_wooden_rifle.png\`). That is the same substitution
\`itemImageHelper\` makes when it hands the image to Discord.

**What can carry an image today.** The dashboard's upload route accepts the
${activityCount} ids listed in [the index at the end](#uploadable-ids) — the
gear, consumables, zones, catches and materials of the three activities — plus
every item in a guild's shop, keyed by its plain \`itemId\`. The other sections
(relics, pets, seasonal event items, daily drops) are named in the game data and
rendered as text; art for them needs the renderer taught to ask for it first.

## 🏹 Hunting

${huntSections()}
## 🎣 Fishing

${fishSections()}
## ⛏️ Mining

${mineSections()}
## 🗺️ Exploring

${exploreSections()}
## 🧪 Materials

Crafting materials, dropped by the system named. The tier beside each name is
its rarity band.

${materialSections()}
## 🔗 Cross-System

Made from the materials of one system and spent in another.

${section('Consumables', rowsOf(cross.CROSS_CONSUMABLES))}
${section('Craft Recipes', rowsOf(cross.CROSS_CRAFT_RECIPES))}
## 🛒 Shop

Seeded into every guild's shop by \`ensureDefaultShopItems\`. A guild admin can
add their own on top of these, and those carry whatever id the admin gives them.

${shopSections()}
## 🐾 Pets

${section('Pets', rowsOf(PET_DEFINITIONS, { idField: 'petId' }))}
## 🎁 Daily Login Drops

${section('Standard Drops', rowsFrom(DROP_TABLE, { idField: 'itemId' }))}
${section('Streak Milestone Drops', rowsFrom(RARE_DROP_TABLE, { idField: 'itemId' }))}
## 🎉 Seasonal Events

Each event runs on its own currency and loot box. Event items live in the
inventory like any other.

${seasonalSections()}
## 📇 Named Content Without Item Images

Named in the data and shown in text, but nothing asks the image system for these
today.

${flavourSections()}
## Uploadable IDs

The exact set the upload route validates against — ${activityCount} ids, from
\`ACTIVITY_ITEM_IDS\` in src/data/activityItems.js.

\`\`\`
${uploadableIndex()}
\`\`\`
`;

    const current = fs.existsSync(DOC_PATH) ? fs.readFileSync(DOC_PATH, 'utf8') : '';
    return { current, next: doc };
}

function main() {
    const { current, next } = buildDoc();
    const check = process.argv.includes('--check');

    if (check) {
        if (current === next) {
            console.log('docs/ECONOMY_ITEMS.md is up to date.');
            return;
        }
        console.error('docs/ECONOMY_ITEMS.md is out of date — run `npm run docs:items`.');
        process.exitCode = 1;
        return;
    }

    fs.mkdirSync(path.dirname(DOC_PATH), { recursive: true });
    fs.writeFileSync(DOC_PATH, next);
    const rows = (next.match(/^\| `/gm) || []).length;
    console.log(`Wrote docs/ECONOMY_ITEMS.md — ${rows} entries.`);
}

if (require.main === module) main();

module.exports = { buildDoc, renderTable, section, uploadableIndex, escapeCell, DOC_PATH, BANNER };
